CREATE DATABASE IF NOT EXISTS shortulr;
USE shortulr;

CREATE TABLE IF NOT EXISTS shorter (
    id VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
    url VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(255) NOT NULL UNIQUE
);
